### ISSUE TITLE
User can view the quote of the day

### ISSUE THREAD

**Issue by heerakmoon** [heerakmoon/AJAX-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the quote of the day

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user opens the application, the quote of the day will be visible on the home page

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![mobile-home](https://user-images.githubusercontent.com/113075380/222237029-bbd4bf9d-8f7f-4bd8-9a45-bee4f5179988.JPG)
![desktop-home](https://user-images.githubusercontent.com/113075380/222237491-f2e25903-61bd-401d-870b-ae2db2de577f.JPG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create header element with logo
- [x] Add navbar for desktop in the header
- [x] Add a 'div[data-view="home"]' to the HTML
- [x] Create an input for the search bar
- [x] Create the div for the 'Quote of the Day'
- [x] Create the 'Guess' button
- [x] Create the navbar for mobile view
- [x] Add styling to match wireframes
- [x] Submit an AJAX request for a random quote for 'the quote of the day'
 - [x] Make sure the quote is not the same as the previous day's
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Fix errors
- [x] Test all functionality again in a private browsing session.
